### ISSUE TITLE
hbb validation fails when webvtt (codec=wvtt) configured for subtitle output

### ISSUE THREAD

**Issue by AlaguSundari59** [Dash-Industry-Forum/HbbTV_DVB#19]
when Subtitle configured with "WebVTT" output segments, the mpd has  

<AdaptationSet
			codecs="wvtt"
			contentType="text"
			id="3"
			lang="eng"
			mimeType="application/mp4"

HbbTv expects only "stpp" (TTML output)  as codec for subtitle. So it reported error for webVTT. 
Is this expected?

**Comment by AlaguSundari** [comment]
no response yet???

**Comment by eceozturk** [comment]
This check is implemented not for HbbTV but for DVB DASH specification. As far as I can see in the code the error is printed for DVB profiles. 

Could it be that:
1. the tested MPD contains a DVB profile in the @profiles attribute or 
2. when testing "DVB" was selected from the "Enforce profile(s)" (when clicked on the Settings icon on the webpage)?

If either of them is correct, then the printed error is valid.

**Comment by eceozturk** [comment]
Closing as there was no further feedback.
